# The base unit of measurement is meters
/**:
  ros__parameters:
    wheel_radius: 0.0033
    track_width: 0.16
    motor_cmd_max: 265
    motor_cmd_per_rad_sec: 0.024
    encoder_ticks_per_rad: 651.898646904 # 2^12 / (2 * pi)
    collision_radius: 0.11