/**:
  ros__parameters:
    frequency: 200.0
    x: -0.5 
    y: 0.7 
    theta: 1.28
    arena_x_length: 5.0
    arena_y_length: 5.0
    obstacles/x: [-0.5, 0.8, 0.4]
    obstacles/y: [-0.7, -0.8, 0.8]
    obstacles/r: 0.038